apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-oidc-script-based-protocol-mapper-configmap
binaryData:
  oidc-script-based-protocol-mapper.jar: {{ required "provider jar missing" (.Files.Get "files/providers/oidc-script-based-protocol-mapper.jar") | b64enc }}
