version:
  image:
    name: alpine/git:1.0.7
    entrypoint: [""]
  script: git describe --always --tags > version
  artifacts:
    paths:
      - version
  rules:
    - if: '$CI_COMMIT_TAG'

push-helm-charts:
  image:
    name: registry.eu-1.deranged.dk/recloud-public/utilities:1.0.0
  needs: ["version"]
  script:
    - pushChartToGitlabRegistry charts/os2adgang-pilot `cat version`
  rules:
    - if: '$CI_COMMIT_TAG'

build-admin-ui:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  needs: ["version"]
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR/admin/ui
      --cache=true
      --destination $CI_REGISTRY_IMAGE/admin-ui:latest
      --destination $CI_REGISTRY_IMAGE/admin-ui:`cat version`
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - ./admin/ui/**/*

build-admin-api:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  needs: ["version"]
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR/admin/api
      --cache=true
      --destination $CI_REGISTRY_IMAGE/admin-api:latest
      --destination $CI_REGISTRY_IMAGE/admin-api:`cat version`
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - ./admin/api/**/*
