version:
  image:
    name: alpine/git:1.0.7
    entrypoint: [""]
  script: git describe --always --tags > version
  artifacts:
    paths:
      - version
  rules:
    - if: '$CI_COMMIT_TAG'

push-helm-charts:
  image:
    name: registry.eu-1.deranged.dk/recloud-public/utilities:1.0.0
  needs: ["version"]
  script:
    - pushChartToGitlabRegistry charts/os2adgang-pilot `cat version`
  rules:
    - if: '$CI_COMMIT_TAG'
