apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.admin.api.domain | default (print "api.admin." .Values.domain) }}
  annotations:
    {{- if and .Values.ingress .Values.ingress.annotations }}
{{ .Values.ingress.annotations | toYaml | indent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  {{- if and .Values.ingress .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.admin.api.domain | default (print "api.admin." .Values.domain) }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-admin-api
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.admin.api.domain | default (print "api.admin." .Values.domain) }}
      secretName: {{ .Values.admin.api.domain | default (print "api.admin." .Values.domain) }}-tls
