server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html/;
    index index.html;
    error_page 404 /404.html;

    gzip on;
    gzip_types text/plain application/json application/javascript text/css image/svg+xml;

    location ~* \.(png|ico|jpg|jpeg)$ {
        # Some images are not in /images
        expires 1d;
        add_header Cache-Control "public";
    }

    location ~* \.(js|css)$ {
        # Env var replacement
        sub_filter_once off;
        sub_filter_last_modified on;
        sub_filter_types application/javascript text/html;
        sub_filter 'PUBLIC_OIDC_AUTH_CLIENT_ID' '${PUBLIC_OIDC_AUTH_CLIENT_ID}';
        sub_filter 'PUBLIC_OIDC_AUTH_AUTHORITY' '${PUBLIC_OIDC_AUTH_AUTHORITY}';
        sub_filter 'PUBLIC_KEYCLOAK_API_BASEURL' '${PUBLIC_KEYCLOAK_API_BASEURL}';
        sub_filter 'PUBLIC_KEYCLOAK_REALM_BASEURL' '${PUBLIC_KEYCLOAK_REALM_BASEURL}';
        sub_filter 'PUBLIC_API_BASEURL' '${PUBLIC_API_BASEURL}';

        # JS and CSS files are compiled with a hash in the name, can be eternal! Hash changes if contents change.
        expires 10y;
        add_header Cache-Control "public";
    }
}
