on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io

name: Build and publish Adgangskomponent
jobs:
  chart:
    name: Helm Chart - build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
      - name: Install helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 #v3
        with:
          version: 4.2.0
      - name: Build Chart
        working-directory: charts/os2adgang-pilot/
        run: |
          declare NAME
          declare VERSION
          NAME=$(yq '.name' < Chart.yaml)
          VERSION=`git describe --always --tags`

          # Override version in Chart
          yq -i ".version = \"$VERSION\"" Chart.yaml;

          # Override repository references in values file to this repository
          yq -i ".admin.ui.image.repostiory = \"${{ env.REGISTRY }}/${{ github.repository }}/admin-ui\"" values.yaml
          yq -i ".admin.api.image.repostiory = \"${{ env.REGISTRY }}/${{ github.repository }}/admin-api\"" values.yaml

          echo "Checking if helm chart exists: $NAME $VERSION (${{ steps.meta.outputs.tags }})"

          declare REPO="oci://${{ env.REGISTRY }}/${{ github.repository }}"

          set +e
          # we check if the image and version already exists
          helm pull --username ${{ github.actor }} --password "${{ secrets.GITHUB_TOKEN }}" --repo "$REPO" --version "$VERSION" "$NAME"
          declare IMAGE_FOUND_STATUS=$?
          set -e

          if [ $IMAGE_FOUND_STATUS == 0 ]; then
              # seems image was already pushed, so we exit
              echo "Chart exists - not pushing new chart";
              exit 0
          fi
          echo "Chart does not exist in registry - building new helm chart";

          helm dependencies update || true
          helm package .

          declare PACKAGE=$NAME-$VERSION.tgz
          helm push --username ${{ github.actor }} --password "${{ secrets.GITHUB_TOKEN }}" $PACKAGE $REPO

          echo "Helm chart built and pushed";

  admin-ui:
    name: Adminpanel UI image - build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          flavor: |
            latest=false
          images: ${{ env.REGISTRY }}/${{ github.repository }}/admin-ui
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: Login to registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc #v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: admin/ui/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  admin-api:
    name: Adminpanel API image - build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          flavor: |
            latest=false
          images: ${{ env.REGISTRY }}/${{ github.repository }}/admin-api
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: Login to registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc #v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: admin/api/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
